#!/bin/sh

# Given a database backup this will load it fresh for
# you. Does not yet handle tennis correctly

BACKUP=$1

if [ -z "$BACKUP" ]; then
    echo "Needs a PostgreSQL dump file as imput"
    exit 0
fi

NAME=$(basename $BACKUP | sed 's/\_production.*/_development/')

if [ $? = 0 ]; then
  EXISTING=$(psql -l | grep $NAME)
  if [ $? = 0 ]; then
    echo "Removing existing $NAME"
    dropdb $NAME
  fi
fi

echo "Creating a new $NAME"
createdb $NAME

echo "Restoring data into $NAME"
pg_restore -O -F c -d $NAME $BACKUP
